{{- if .Values.connectGatewayUsers }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: connect-gateway-cluster-admin-helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
{{- range .Values.connectGatewayUsers }}
  - kind: User
    name: {{ . }}
{{- end }}
{{- end }}